# Generated by Django 2.2.4 on 2019-08-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
