# Generated by Django 2.2.4 on 2019-08-14 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESE', '0002_auto_20190814_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ESE.Module'),
        ),
    ]
