# Generated by Django 2.2.4 on 2019-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESE', '0005_auto_20190814_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
