# Generated by Django 2.1.7 on 2019-08-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESE', '0006_rating_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
