# Generated by Django 2.1.7 on 2019-08-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESE', '0007_auto_20190816_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='module',
            field=models.ManyToManyField(blank=True, related_name='students', to='ESE.Module'),
        ),
    ]
